src/store/blog/index.js

Reverts arrogant-ant/parkspot#165

Revert "typo fix"

---

src/components/templates/TemplateAbout.vue

@media used & font-size increased for Desktop

---

src/components/templates/TemplateNearBy.vue

Breadcrumb size issue resolved

Breadcrumb size

---

src/components/templates/TemplateFeatureHome.vue

Removed extra padding from top and bottom.

Feature Padding issue resolved

---

src/components/organisms/OrganismHomeCard.vue

Title Change

---

src/services/api.js
src/store/user/index.js

bug : data not loading in login immediately fixed

Bugfix: data not loading in login immediately

---

src/components/organisms/OrganismHomeCard.vue

Spot Owner Text Changed

---

src/components/templates/TemplateFaq.vue

FAQ ParkSpot Paragraph Changed.

FAQ ParkSpot Para Changed

---

src/components/templates/TemplateAbout.vue

About Us Section Paragraph has been changed.

About Us Para Changed

---

src/components/organisms/OrganismHomeCard.vue

Search Button Text Has Been Changed.

Search Button Text Changed

---

src/components/organisms/OrganismHomeCard.vue

Home Card Button Text Has Been Changed.

Button Text changed

---

src/components/organisms/OrganismHomeCard.vue

Home Heading Text Has Been Changed.

Heading Text Changed

---

src/components/organisms/OrganismHomeCard.vue

Text Changed

---

src/components/organisms/OrganismHomeCard.vue
src/components/organisms/OrganismSpotRateCard.vue

Spot Rate Card Bold Text

---

src/components/templates/TemplateSpotDetail.vue
src/views/PageSpotDetail.vue

SO details will be shown by default to logged in admin users.

updated admin check

---

src/components/templates/TemplateNearBy.vue

Near By Header issue Has Been Resolved.

Near By Header issue Resolved

---

src/components/templates/TemplateSpotDetail.vue

Reverts arrogant-ant/parkspot#267

Revert "google map link added"

---

src/components/templates/TemplateSearchPortal.vue

Agent List Added

---

package-lock.json
package.json
src/components/atoms/AtomCheckbox.vue
src/components/atoms/AtomRadioButton.vue
src/components/molecules/MoleculeSRPCard.vue
src/components/templates/TemplateSrp.vue
src/store/map/index.js
src/views/PageSrp.vue
yarn.lock

Revamp of Srp page
- srp card
- infinite scroll
- filter added

Srp scroll

---

src/components/organisms/OrganismTestimonialSwiper.vue

Current Review Dot Color Changed

---

.env.development
.env.production
package-lock.json
package.json
public/index.html
src/components/extras/SearchInput.vue
src/store/map/index.js
vue.config.js
yarn.lock

Map google

---

src/components/templates/TemplateSpotDetail.vue
src/constant/enums.js

1. Add KYC status label.
2. Add updatedAt in sdp admin details

Add updatedAt in sdp admin details

---

src/components/atoms/AtomButton.vue
src/components/atoms/AtomCheckbox.vue
src/components/atoms/AtomIcon.vue
src/components/atoms/AtomTooltip.vue
src/components/templates/TemplateSearchPortal.vue

Replacing is-warning class

---

src/components/extras/LoaderModal.vue

loader animation changed now it contains logo inside the loader

Loader animation

---

src/components/molecules/MoleculeBlogCard.vue

Action applied on (Title & Author) & hover added.

Action applied & hover added

---

src/components/templates/TemplateBookingPortal.vue
src/constant/enums.js
src/router/routes.js
src/store/bookingPortal/index.js
src/views/BookingPortal.vue
vue.config.js

Add booking status dropdown in booking portal (/internal/booking-portal)

added status dropdown

---

src/components/templates/TemplateBookingPortal.vue
src/constant/enums.js

Add payment periodicity dropdown in booking portal.

Add payment periodicity dropdown in booking portal

---

src/firebase.js
src/router/routes.js
src/store/sdp/index.js
src/store/user/index.js
src/views/PageNearBy.vue

Restructure firebase utils methods.  Expose a method to get values from firebase realtime database.
#code_cleanup

Restructure firebase utils methods. 

---

src/App.vue
src/components/extras/NavbarBody.vue
src/components/extras/navbar.scss
src/components/organisms/OrganismBlogParkingChallenges.vue
src/components/organisms/OrganismContactUs.vue
src/components/organisms/OrganismParkingChallengesPageDesign.vue
src/components/templates/TemplateError.vue
src/components/templates/TemplateFooter.vue
src/components/templates/TemplateThankYou.vue
src/store/config/index.js
src/store/index.js

1. Created Firebase config store.
2. Picking helpline number from config

Helpline number

---

src/components/molecules/MoleculeSearchBox.vue

Increase Searchbox (used in booking portal) accessibility by enabling search on enter press.

Call search action on press of enter.

---

src/components/templates/TemplateHomeBanner.vue
src/views/PageHome.vue
src/views/PageSearchPortal.vue

flytosrp event was not being emitted but was being called.
This was creating runtime warnings

remove unused code.

---

public/sitemap.xml
src/components/templates/TemplateFooter.vue
src/router/routes.js
vue.config.js

Add Serve side rendering page for hyd.

Add Serve side rendering page for hyd.

---

src/components/atoms/AtomDatePicker.vue
src/components/templates/TemplateBookingPortal.vue

* store local state
* add number validation for rent, conv fee and base amount.
* Move Rent Details up in the UI.
* Add link to sdp from booking portal

Booking portal enhancements

---

src/services/api.js

return api error data from service

return api error data from service

---

src/views/PageSearchPortal.vue

mobile input placeholder added

---

src/components/extras/MapContainer.vue
src/components/organisms/OrganismContactForm.vue
src/store/sdp/index.js

1. Add map marker popup
2. Remove email validation

Map marker popup

---

src/components/templates/TemplateSearchPortal.vue

agent dropdown place changed

---

src/components/templates/TemplateSearchPortal.vue
src/views/PageSearchPortal.vue

* Resized column width and reduced page size.
* Removed whitespace from mobile number.

Resized search portal table so that its comfortably visible in small screen.

---

src/components/atoms/AtomDatePicker.vue
src/components/extras/LoaderModal.vue
src/components/templates/TemplateEditProfile.vue
src/components/templates/TemplateSpotDetail.vue
src/router/routes.js
src/store/sdp/index.js
src/views/BookingPortal.vue
src/views/PageContactUs.vue
src/views/PageSOPortal.vue
src/views/PageSpotDetail.vue
src/views/PageSrp.vue
src/views/PageVOPortal.vue

Calendar added

---

src/components/templates/TemplateTerms.vue

TnC text Updated. VO & SO Heading highlighted.

---

src/components/templates/TemplateFooter.vue
src/components/templates/TemplatePrivacyPolicy.vue
src/constant/constant.js
src/router/routes.js
src/views/PagePrivacyPolicy.vue

New-Privacy-Policy-Webpage Added

---

src/components/templates/TemplateBookingPortal.vue
src/store/bookingPortal/index.js

Add remark field in booking portal.

---

src/components/templates/TemplateSpotDetail.vue
src/store/sdp/index.js
src/views/PageSpotDetail.vue

Show Spot remark in SDP owner details.

---

src/components/extras/NavbarBody.vue

Add Faq nav

---

src/components/templates/TemplateThankYou.vue

contact display text msg  updated

---

src/components/templates/TemplateFaq.vue

new faqlists,contact us link added & AtomParagraph used

---

src/components/templates/TemplateBookingPortal.vue

Reverts arrogant-ant/parkspot#395

Revert "Updated booking details contract to fetch payment from booking object."

---

src/components/extras/NavbarBody.vue

mweb FAQ added

---

src/components/templates/TemplateAbout.vue

margin left,right used &  gap value reduced

---

src/components/templates/TemplateThankYou.vue

media query used

---

src/components/templates/TemplateSpotDetail.vue

disabled right scroll p3 issue resolved

---

src/components/templates/TemplateBlogHome.vue

blog page right scroll issue resolved

---

src/components/templates/TemplateFooter.vue

Footer Contact us link added

---

src/components/organisms/OrganismContactForm.vue
src/includes/VeeValidate.js

Address Validation Added

---

src/components/templates/TemplateVOPortal.vue
src/store/user/index.js

It will be enabled after location picker is improved.

Commented location details from Request spot page.

---

src/components/templates/TemplateBookingPortal.vue
src/constant/enums.js

SO Changes & Rent + SD new text used

---

src/components/templates/TemplateFooter.vue

New text added

---

src/components/templates/TemplateSearchPortal.vue

Reverts arrogant-ant/parkspot#419

Revert "Add ankit as agent."

---

src/components/templates/TemplateSearchPortal.vue

Reverts arrogant-ant/parkspot#421

Revert "Revert "Add ankit as agent.""

---

package-lock.json
src/components/templates/TemplateBookingPortal.vue
src/store/bookingPortal/index.js
src/views/BookingPortal.vue
yarn.lock

Agents selection

---

src/views/BookingPortal.vue

This PR replaced error text displayed on Booking portal with ErrorAlert dialog.

replaced error text of booking portal with error alert

---

src/constant/enums.js
src/router/routes.js
src/store/agentBook/index.js
src/store/index.js
src/views/RegisterRequest.vue

Integrating Apis for GET and POST, 
adding enum: Parkingrequeststatus
adding route : parkspot.in/internal/register-request

Backend for agent Book

---

src/views/RegisterRequest.vue

This contains only the frontend for agent Book.

Frontend for Vehicle Owner Registration

---

src/components/molecules/MoleculeSearchBox.vue
src/store/bookingPortal/index.js
src/store/searchPortal/index.js
src/views/BookingPortal.vue
src/views/PageSearchPortal.vue

Review Video
[recording-2024-11-09-15-41-37.webm](https://github.com/user-attachments/assets/6f6ce243-9008-4b26-9d51-622d3f151cd8)

fix: resolve bug in search-box-molecule

---

src/components/templates/TemplateSearchPortal.vue

* feat: add close icon to show summary modal
* fix: formate code

feat: add close icon to show summary modal (#458)

---

src/components/booking-portal/ActiveBookings.vue

Add status column to booking portal table

Add status column to booking portal table (#462)

---

src/components/extras/NavbarBody.vue
src/components/extras/navbar.scss

Update Navigation Menu

---

src/constant/enums.js
src/store/searchPortal/index.js
src/views/PageSearchPortal.vue

**Description**:
This PR addresses two main improvements:
1. **Dialog Box Error**: Resolved an error that was causing issues within the dialog box. This fix ensures smoother user interaction and consistent behavior.
2. **Tab Navigation in URL**: Added tab state to the URL, allowing direct linking and better persistence of active tab state. Users can now navigate directly to a specific tab using the URL parameters.
**Changes Made**:
- Updated `created` hook to manage initial state and prevent unnecessary re-renders.
- Added logic to update the URL based on the selected tab without triggering component remounting.
- Improved error handling in the dialog box.

Fix dialog box error and add tab navigation to URL

---

src/views/PageSearchPortal.vue

Resolve the bug in the tab functionality on the search portal page.

Resolve the bug in the tab functionality on the search portal page.

---

src/constant/enums.js
src/router/routes.js
src/store/index.js
src/store/spotRequests/index.js
src/views/PageSpotRequest.vue

Created a Page for spot request

Add Page to show all spot requests

---

public/index.html
src/components/global/TestimonialCard.vue
src/components/global/TestimonialSection.vue
src/components/templates/TemplateVOPortal.vue
src/constant/constant.js

Page vo portal/benefits

---

src/components/templates/TemplateVOPortal.vue
src/components/vo-portal/WhatNext.vue
src/constant/constant.js
vue.config.js

Create What's Next section in Page VO Portal

---

.env.development
.env.production
src/components/extras/MapContainer.vue

This PR introduces functionality to securely retrieve the Mapbox access token from Firebase.

Retrieve Map Access Token from Firebase

---

src/components/extras/MapContainer.vue

replaced setMapAccessTokenInCookies() with this.setMapAccessTokenInCookies()

fix bug while using setMapAccessTokenInCookies method

---

src/components/templates/TemplateBookingPortal.vue
src/constant/enums.js

Add Payment Type Column

---

src/components/atoms/AtomInput.vue
src/components/atoms/AtomTextarea.vue
src/components/molecules/MoleculeNameInput.vue

- Updated `MoleculeNameInput` and `AtomTextarea` components to properly handle `v-model` using `modelValue` and `update:modelValue`.  
- Ensured `@input` and `@update:modelValue` propagate changes correctly.  
- Fixed event bindings to ensure form fields react to changes as expected.

Fix: Form Input Not Updating Properly

---

src/components/atoms/AtomInput.vue
src/components/atoms/AtomTextarea.vue
src/components/molecules/MoleculeNameInput.vue
src/components/organisms/OrganismContactForm.vue

**Description:**
- Fixed issue with form validation in `OrganismContactForm.vue`.
- Replaced incorrect usage of `this.$refs.observer.validate()` with proper validation handling.

fix bug in form submit

---

src/components/extras/navbar.scss

fix text logo width at desktop screen

---

src/components/booking-portal/ActiveBookings.vue
src/components/templates/TemplateFaq.vue

FAQ Bug is resolved [All Expandable components of Frequently asked question page in UAT is by default open with no down icon].
Booking-portal Bug is fixed [Input textbox in booking portal is very small(uat).]

Resolving FAQ + booking portal bugs

---

src/components/molecules/MoleculeBlogCard.vue
src/components/templates/TemplateSearchPortal.vue
src/components/templates/TemplateSpotDetail.vue

Read more in blogs feature is added.
Search-portal bugs are fixed [Latlong + comments].

Resolving search portal bugs

---

src/components/atoms/AtomSelectInput.vue
src/components/templates/TemplateSearchPortal.vue

the clearfilter doesn't work for now.

Search portal filter

---

src/components/templates/TemplateSpotDetail.vue
src/constant/constant.js
src/store/sdp/index.js
src/views/PageSpotDetail.vue

Add Table to Show In-progress Bookings at SDP Page

---

src/components/templates/TemplateSearchPortal.vue
src/store/searchPortal/index.js
src/store/user/index.js
src/views/PageSearchPortal.vue

Added "Assign to me" Button for Agents

---

src/components/atoms/AtomTextarea.vue
src/components/templates/TemplateSearchPortal.vue

Add Pop-up to Show Client Mobile Number and Add Note

---

src/components/extras/MapContainer.vue

change map box min-height from 450px to 550px

---

src/components/extras/NavbarBody.vue
src/store/user/index.js

Reverts arrogant-ant/parkspot#574

Revert "Dropdown to access all the /internal routes"

---

src/components/global/ImageUpload.vue
src/services/ImageUploadService.js
src/store/reviewSpot/index.js
src/views/PageSpotRequest.vue

Common Template Image Upload adding to reviewSpot

heic format images are also uploaded

---

src/components/global/FormInput.vue
src/components/global/ImageUpload.vue
src/components/global/MultiSelectInput.vue
src/components/global/SelectInput.vue
src/components/global/TestimonialCard.vue
src/components/global/Whats_Next.vue
src/components/so-portal/RegisterRequestForm.vue
src/components/templates/TemplateSOPortal.vue
src/constant/constant.js
src/services/ImageUploadService.js
src/store/reviewSpot/index.js
src/validationSchemas.js
src/views/PageSOPortal.vue
src/views/PageSpotRequest.vue
src/views/ReviewSpot.vue

Common Template Image Upload adding to reviewSpot

Register Spot Page form 

---

public/.well-known/assetlinks.json
public/apple-app-site-association

Updated assetlinks.json and apple-app-association to allow deeplink for register spot.

updated assetlinks.json and apple-app-association

---

src/components/global/TestimonialCard.vue
src/components/global/TestimonialSection.vue
src/constant/constant.js
src/router/routes.js
src/views/AutomateParking.vue
src/views/PageSocietyParking.vue

Create Parking Automation Page for Societies

---

src/store/reviewSpot/index.js

Reverts arrogant-ant/parkspot#618

Revert "Added timeout in pulish spot api"

---

src/views/ReviewSpot.vue

Reverts arrogant-ant/parkspot#617

Revert "Add validation check before showing confirmation popup"

---

src/views/ReviewSpot.vue

Reverts arrogant-ant/parkspot#623

Revert "Revert "Add validation check before showing confirmation popup""

---

src/store/reviewSpot/index.js

Reverts arrogant-ant/parkspot#622

Revert "Revert "Added timeout in pulish spot api""

---

src/views/ReviewSpot.vue

Removed extra address field and formate form

---

src/views/PageKYCStatus.vue

Fix Image Zoom Bug
